"""initial

Revision ID: 22ad1b827307
Revises: 
Create Date: 2026-05-22 04:10:08.066025

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '22ad1b827307'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issues',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('creator_id', sa.BigInteger(), nullable=False),
    sa.Column('assignee_name', sa.String(length=100), nullable=True),
    sa.Column('executor_name', sa.String(length=100), nullable=True),
    sa.Column('executor_type', sa.String(length=20), nullable=True),
    sa.Column('executor_note', sa.Text(), nullable=True),
    sa.Column('related_files', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence_note', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('failed_attempts', sa.Text(), nullable=True),
    sa.Column('final_solution', sa.Text(), nullable=True),
    sa.Column('reusable', sa.Boolean(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('activity_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("executor_type IN ('human', 'ai_window', 'role', 'tool')"),
    sa.CheckConstraint("status IN ('open', 'in_progress', 'resolved', 'archived')"),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_issues_creator', 'issues', ['creator_id'], unique=False)
    op.create_index('idx_issues_status', 'issues', ['status'], unique=False)
    op.create_index('idx_issues_workspace', 'issues', ['workspace_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('issue_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('assignee_name', sa.String(length=100), nullable=True),
    sa.Column('executor_name', sa.String(length=100), nullable=True),
    sa.Column('executor_type', sa.String(length=20), nullable=True),
    sa.Column('executor_note', sa.Text(), nullable=True),
    sa.Column('related_files', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence_note', sa.Text(), nullable=True),
    sa.Column('activity_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("executor_type IN ('human', 'ai_window', 'role', 'tool')"),
    sa.CheckConstraint("status IN ('todo', 'doing', 'done')"),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_index('idx_issues_workspace', table_name='issues')
    op.drop_index('idx_issues_status', table_name='issues')
    op.drop_index('idx_issues_creator', table_name='issues')
    op.drop_table('issues')
    op.drop_table('workspaces')
    op.drop_table('users')
    # ### end Alembic commands ###
